version: "3.8"

services:
  frontend:
    container_name: awesome-app-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - 8765:5173
    restart: always
    tty: true
    volumes:
      - ./frontend:/app
      - awesome-app-frontend-node_modules:/app/node_modules
    command: npm run dev

  backend:
    container_name: awesome-app-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3980:3980
    volumes:
      - ./backend:/app
      - awesome-app-backend-node_modules:/app/node_modules
    tty: true
    depends_on:
      - database
    expose:
      - 3980
    environment:
      APP_PORT: 3980
      VUE_APP_ORIGIN: "http://localhost:8765"
      DB_HOST: "database"
      DB_PORT: 5678
      DB_DATABASE: "awesome_app_db"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "password"

  database:
    image: postgres:15
    container_name: awesome-app-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "awesome_app_db"
      TZ: "Asia/Tokyo"
    ports:
      - 5678:5432

volumes:
  awesome-app-frontend-node_modules:
  awesome-app-backend-node_modules:
  postgres_data:
